# Generated by Django 3.1.1 on 2020-09-25 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Anecdotes', '0007_auto_20200916_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='anecdote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anecdotes.anecdote'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
